name: otolink
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  cached_network_image: ^3.3.1
  lottie: ^2.4.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  shared_preferences: ^2.3.2
  image_picker: ^1.0.4
  http: ^1.6.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animation/
    - assets/data/

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png
  android_12:
    image: assets/images/logo.png
    icon_background_color: "#FFFFFF"
  web: false